name: .NET

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup working directory
        uses: actions/checkout@v3  # Use v3 for this specific step
        with:
          path: ./backend  # Define the path to your project directory
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        working-directory: ./backend  # Specify working directory for commands
        run: dotnet restore
      - name: Build
        working-directory: ./backend  # Specify working directory for commands
        run: dotnet build --no-restore
      - name: Test
        working-directory: ./backend  # Specify working directory for commands
        run: dotnet test --no-build --verbosity normal
